- name: Create folder - {{item.dir}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.13.120:8080
    user: admin
    password: "{{jenkins_password}}"
  loop:
    - CIPipelines

- name: create pipeline jobs
  ansible.builtin.include.tasks: pipeline.yml
  loop:
    - {name: "frontend", dir: "CIPipelines"}
    - {name: "cart", dir: "CIPipelines"}
    - {name: "catalogue", dir: "CIPipelines"}
    - {name: "user", dir: "CIPipelines"}
    - {name: "payment", dir: "CIPipelines"}
    - {name: "shipping", dir: "CIPipelines"}