- name: create config file
  ansible.builtin.template:
    src: m-job.xml
    dest: /tmp/m-job.xml

- name: Create folder
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.13.120:8080
    user: admin
    password: "{{jenkins_password}}"