- name: create config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job-{{item.name}}.xml

- name: Create folder - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job-{{item.name}}.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.13.120:8080
    user: admin
    password: "{{jenkins_password}}"